// frontend-vue/healthinsurance-hub/src/components/search/ResultsList.vue
<template>
  <div>
    <div v-if="error" class="text-center py-8 text-red-500">
      خطا در دریافت اطلاعات: {{ error }}
      <button @click="retrySearch" class="mt-4 px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600">
        تلاش مجدد
      </button>
    </div>
    
    <div v-else-if="loading" class="space-y-5">
      <div v-for="n in 5" :key="n" class="bg-white rounded-xl shadow-sm p-4">
        <div class="grid md:grid-cols-[1fr_auto] gap-4">
          <div>
            <div class="h-6 bg-gray-200 rounded w-3/4 mb-2"></div>
            <div class="h-4 bg-gray-200 rounded w-full mb-4"></div>
            
            <div class="flex flex-wrap gap-2 mb-4">
              <div v-for="i in 2" :key="i" class="h-6 bg-gray-200 rounded w-24"></div>
            </div>
            
            <div class="h-4 bg-gray-200 rounded w-1/2"></div>
          </div>
          
          <div class="flex items-center">
            <div class="h-10 bg-gray-200 rounded w-full"></div>
          </div>
        </div>
      </div>
    </div>
    
    <div v-else-if="centers.length === 0" class="text-center py-12">
      <h3 class="text-xl font-semibold mb-2">مرکزی یافت نشد</h3>
      <p class="text-gray-600">
        متأسفانه با فیلترهای انتخاب شده هیچ مرکز درمانی یافت نشد.
      </p>
    </div>
    
    <div v-else class="space-y-5">
      <div 
        v-for="(center, index) in centers" 
        :key="center.id" 
        class="bg-white rounded-xl shadow-sm overflow-hidden"
      >
        <div class="grid md:grid-cols-[1fr_auto] gap-4 p-4">
          <div>
            <h3 class="text-lg font-bold mb-1">{{ center.name }}</h3>
            <p class="text-gray-600 text-sm mb-3 line-clamp-2">
              {{ center.address }}
            </p>
            
            <div class="flex flex-wrap gap-2 mb-3">
              <span 
                v-for="insurance in center.accepted_insurance" 
                :key="insurance.id"
                class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800"
              >
                {{ insurance.name }}
                <span v-if="insurance.services.length > 0">
                  ({{ insurance.services.map(s => getServiceName(s)).join('، ') }})
                </span>
              </span>
            </div>
            
            <p v-if="center.phone" class="text-gray-600 text-sm">
              تلفن: {{ center.phone }}
            </p>
          </div>
          
          <div class="flex items-center">
            <button 
              class="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium hover:bg-gray-100 whitespace-nowrap"
            >
              <i class="fas fa-directions ml-2"></i>
              جهت‌یابی
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Props
const props = defineProps<{
  centers: any[]
  loading: boolean
  error: string | null
}>()

// Emits
const emit = defineEmits<{
  (e: 'retry'): void
  (e: 'loadMore'): void
}>()

// Methods
const retrySearch = () => {
  emit('retry')
}

const loadMore = () => {
  emit('loadMore')
}

// Service names mapping
const getServiceName = (service: string) => {
  const serviceNames: Record<string, string> = {
    'dentistry': 'دندانپزشکی',
    'imaging': 'تصویربرداری',
    'lab': 'آزمایشگاه',
    'general': 'معاینه عمومی',
    'specialist': 'معاینه تخصصی'
  }
  return serviceNames[service] || service
}
</script>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>

// frontend/components/search/ResultsList.tsx
'use client';

import { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { getMedicalCenters } from '@/lib/api';
import { MedicalCenter } from '@/lib/types';
import { Skeleton } from '@/components/ui/skeleton';

export function ResultsList({ filters }: { filters?: any }) {
  const [centers, setCenters] = useState<MedicalCenter[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const data = await getMedicalCenters(filters || {});
        setCenters(data);
      } catch (err) {
        setError('خطا در دریافت اطلاعات. لطفاً دوباره تلاش کنید.');
        console.error('Error fetching medical centers:', err);
      } finally {
        setLoading(false);
      }
    };
    
    fetchData();
  }, [filters]);

  if (error) {
    return (
      <div className="text-center py-8 text-red-500">
        {error}
      </div>
    );
  }

  if (loading) {
    return (
      <div className="space-y-6">
        {[...Array(5)].map((_, i) => (
          <Card key={i}>
            <div className="grid md:grid-cols-3 gap-4">
              <div className="md:col-span-2 p-4">
                <Skeleton className="h-6 w-3/4 mb-2" />
                <Skeleton className="h-4 w-full mb-4" />
                <div className="flex flex-wrap gap-2 mb-4">
                  {[...Array(2)].map((_, j) => (
                    <Skeleton key={j} className="h-6 w-24" />
                  ))}
                </div>
                <Skeleton className="h-4 w-1/2" />
              </div>
              <div className="flex items-center justify-center p-4">
                <Skeleton className="h-10 w-full" />
              </div>
            </div>
          </Card>
        ))}
      </div>
    );
  }

  if (centers.length === 0) {
    return (
      <div className="text-center py-12">
        <h3 className="text-xl font-semibold mb-2">مرکزی یافت نشد</h3>
        <p className="text-muted-foreground">
          متأسفانه با فیلترهای انتخاب شده هیچ مرکز درمانی یافت نشد.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {centers.map(center => (
        <Card key={center.id} className="overflow-hidden">
          <div className="grid md:grid-cols-3 gap-4">
            <div className="md:col-span-2">
              <CardHeader>
                <CardTitle className="text-xl">{center.name}</CardTitle>
                <CardDescription>{center.address}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-wrap gap-2 mb-4">
                  {center.accepted_insurance.map(ins => (
                    <Badge key={ins.id} variant="secondary">
                      {ins.name} 
                      {ins.services.length > 0 && 
                        ` (${ins.services.join(', ')})`}
                    </Badge>
                  ))}
                </div>
                {center.phone && (
                  <p className="text-sm text-muted-foreground">
                    تلفن: {center.phone}
                  </p>
                )}
              </CardContent>
            </div>
            <div className="flex items-center justify-center p-4 bg-muted/50">
              <Button variant="outline">جهت‌یابی</Button>
            </div>
          </div>
        </Card>
      ))}
      
      {centers.length >= 10 && (
        <div className="flex justify-center mt-6">
          <Button variant="outline">نمایش بیشتر</Button>
        </div>
      )}
    </div>
  );
}
