// frontend/components/search/ResultsList.tsx
'use client';

import { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { getMedicalCenters } from '@/lib/api';
import { MedicalCenter } from '@/lib/types';
import { Skeleton } from '@/components/ui/skeleton';

export function ResultsList({ filters }: { filters?: any }) {
  const [centers, setCenters] = useState<MedicalCenter[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const data = await getMedicalCenters(filters || {});
        setCenters(data);
      } catch (err) {
        setError('خطا در دریافت اطلاعات. لطفاً دوباره تلاش کنید.');
        console.error('Error fetching medical centers:', err);
      } finally {
        setLoading(false);
      }
    };
    
    fetchData();
  }, [filters]);

  if (error) {
    return (
      <div className="text-center py-8 text-red-500">
        {error}
      </div>
    );
  }

  if (loading) {
    return (
      <div className="space-y-6">
        {[...Array(5)].map((_, i) => (
          <Card key={i}>
            <div className="grid md:grid-cols-3 gap-4">
              <div className="md:col-span-2 p-4">
                <Skeleton className="h-6 w-3/4 mb-2" />
                <Skeleton className="h-4 w-full mb-4" />
                <div className="flex flex-wrap gap-2 mb-4">
                  {[...Array(2)].map((_, j) => (
                    <Skeleton key={j} className="h-6 w-24" />
                  ))}
                </div>
                <Skeleton className="h-4 w-1/2" />
              </div>
              <div className="flex items-center justify-center p-4">
                <Skeleton className="h-10 w-full" />
              </div>
            </div>
          </Card>
        ))}
      </div>
    );
  }

  if (centers.length === 0) {
    return (
      <div className="text-center py-12">
        <h3 className="text-xl font-semibold mb-2">مرکزی یافت نشد</h3>
        <p className="text-muted-foreground">
          متأسفانه با فیلترهای انتخاب شده هیچ مرکز درمانی یافت نشد.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {centers.map(center => (
        <Card key={center.id} className="overflow-hidden">
          <div className="grid md:grid-cols-3 gap-4">
            <div className="md:col-span-2">
              <CardHeader>
                <CardTitle className="text-xl">{center.name}</CardTitle>
                <CardDescription>{center.address}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-wrap gap-2 mb-4">
                  {center.accepted_insurance.map(ins => (
                    <Badge key={ins.id} variant="secondary">
                      {ins.name} 
                      {ins.services.length > 0 && 
                        ` (${ins.services.join(', ')})`}
                    </Badge>
                  ))}
                </div>
                {center.phone && (
                  <p className="text-sm text-muted-foreground">
                    تلفن: {center.phone}
                  </p>
                )}
              </CardContent>
            </div>
            <div className="flex items-center justify-center p-4 bg-muted/50">
              <Button variant="outline">جهت‌یابی</Button>
            </div>
          </div>
        </Card>
      ))}
      
      {centers.length >= 10 && (
        <div className="flex justify-center mt-6">
          <Button variant="outline">نمایش بیشتر</Button>
        </div>
      )}
    </div>
  );
}

// frontend/src/components/search/ResultsList.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import { useSearchStore } from '@/stores/search';
import AppCard from '@/components/base/AppCard.vue';
import AppButton from '@/components/base/AppButton.vue';
import Badge from '@/components/ui/Badge.vue';
import Skeleton from '@/components/ui/Skeleton.vue';

const { t } = useI18n();
const searchStore = useSearchStore();

onMounted(() => {
  searchStore.searchCenters();
});

const loading = computed(() => searchStore.loading);
const centers = computed(() => searchStore.filteredCenters);
const error = computed(() => searchStore.error);
</script>

<template>
  <div>
    <div v-if="error" class="text-center py-8 text-destructive">
      {{ t('common.error') }}: {{ error }}
      <AppButton @click="searchStore.searchCenters()" class="mt-4">
        {{ t('common.retry') }}
      </AppButton>
    </div>

    <div v-else-if="loading" class="space-y-5">
      <AppCard v-for="n in 5" :key="n" class="glass-card animate-slide-up">
        <div class="grid md:grid-cols-[1fr_auto] gap-4 items-center">
          <div class="space-y-2">
            <Skeleton class="h-6 w-3/4" />
            <Skeleton class="h-4 w-full" />
            <div class="flex flex-wrap gap-2 pt-2">
              <Skeleton class="h-6 w-24" />
              <Skeleton class="h-6 w-24" />
            </div>
            <Skeleton class="h-4 w-1/2" />
          </div>

          <div class="flex items-center">
            <Skeleton class="h-10 w-24" />
          </div>
        </div>
      </AppCard>
    </div>

    <div v-else-if="centers.length === 0" class="text-center py-12">
      <h3 class="text-xl font-semibold mb-2">{{ t('search.results.noResults') }}</h3>
      <p class="text-muted-foreground">
        {{ t('search.results.noResultsDescription') }}
      </p>
    </div>

    <div v-else class="space-y-5">
      <AppCard
        v-for="(center, index) in centers"
        :key="center.id"
        class="glass-card overflow-hidden animate-slide-up"
        :style="{ animationDelay: `${index * 0.1}s` }"
      >
        <div class="grid md:grid-cols-[1fr_auto] gap-4">
          <div>
            <h3 class="text-lg font-bold mb-1">{{ center.name }}</h3>
            <p class="text-muted-foreground text-sm mb-3 line-clamp-2">
              {{ center.address }}
            </p>

            <div class="flex flex-wrap gap-2 mb-3">
              <Badge
                v-for="insurance in center.accepted_insurance"
                :key="insurance.id"
                variant="secondary"
                class="text-xs py-1 px-2"
              >
                {{ insurance.name }}
                <span v-if="insurance.services.length > 0">
                  ({{ insurance.services.map(s => t(`search.filters.services.options.${s}`)).join('، ') }})
                </span>
              </Badge>
            </div>

            <p v-if="center.phone" class="text-muted-foreground text-sm">
              {{ t('common.phone') }}: {{ center.phone }}
            </p>
          </div>

          <div class="flex items-center">
            <AppButton
              variant="outline"
              size="sm"
              class="w-full md:w-auto whitespace-nowrap"
            >
              <i class="fas fa-directions ml-2"></i>
              {{ t('search.results.direction') }}
            </AppButton>
          </div>
        </div>
      </AppCard>

      <div v-if="centers.length >= 10" class="flex justify-center mt-6">
        <AppButton variant="outline" @click="searchStore.loadMore()">
          {{ t('search.results.showMore') }}
        </AppButton>
      </div>
    </div>
  </div>
</template>
